### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by Sheelia** [DamienShahan/LostArkFishingBot#1]
throws fishing rods but does not catch fish my resolution 1600x900

**Comment by DamienShahan** [comment]
Hi Sheelia

The fishing bot does not support your resolution yet, however for a donation amount of your choice I would add it 1600x900 to the supported resolutions: https://www.paypal.com/donate/?hosted_button_id=G3GRAKMYJGEMC

Best regards

**Comment by DamienShahan** [comment]
Since there is no response, I will close this.
