### ISSUE TITLE
Problem with latest version

### ISSUE THREAD

**Issue by Nackenkelle** [DamienShahan/LostArkFishingBot#10]
Good evening.
i stuck on a problem with the latest version of the fish bot.
Bot shows that it will repair after 50 throws. but it will repair after every fish ?
is that a bug or can i change it somewhere?

**Comment by DamienShahan** [comment]
Hello,

Thanks for reporting the issue.
An artifact from testing was left over in the code, causing the bot to repair after every fish. It only happend in main.exe, not antiafk.exe.

This has been fixed and a new zip folder (main-v1.5-fixed.zip) has been uploaded on the release page: https://github.com/DamienShahan/LostArkFishingBot/releases/tag/main1.5
