### ISSUE TITLE
file is locked ?

### ISSUE THREAD

**Issue by V4MPZZ** [DamienShahan/LostArkFishingBot#2]
where can i get the password to extract ?

**Comment by DamienShahan** [comment]
Hi,

For a donation amount of your choice, I will send you the password:
https://www.paypal.com/donate/?hosted_button_id=G3GRAKMYJGEMC
Just make sure to enter your E-Mail in the note, so I know it was you.

Cheers

**Comment by DamienShahan** [comment]
Sofar there is only the guide in the .Readme. However I will try record and add a video in the next 24 hours.
