### ISSUE TITLE
Repairs

### ISSUE THREAD

**Issue by Futakashi** [DamienShahan/LostArkFishingBot#21]
can you help or change the auto repair from 50 to 25? or 20? my rod breaks before 30 so 50 is too long

**Comment by geniusjoe** [comment]
https://github.com/DamienShahan/LostArkFishingBot/blob/39d6dfb267b1cf31922e7530aefb15975c1c7ab9/main.py#L141
`
    if counter % 25 == 0 and (idletimer == 500 or flag == "pulled"):
`
I think you can just modify fishing counter from 50 to 25, then run main.py again.
