### ISSUE TITLE
is it detected by EAC ?

### ISSUE THREAD

**Issue by Denver3D** [DamienShahan/LostArkFishingBot#6]
hello first thank you for your hard work, and I was wondering if it's detected by EAC ?

**Comment by DamienShahan** [comment]
Hi, Thanks :)

I have not received any reports of anyone getting banned using it.
Me and my guildies use it a lot as well.

I don't believe there is really anything to detect either. 
The bot takes a screenshot and uses image recognition to find the exclamation point from fishing.
Once it "sees" the exclamation point, it then sends a keyboard click (E) to your computer.

It never tries to read anything from your RAM, or do any other bannable / detectable action. 
It really is just 1. take screenshot, 2, find explamation point in screenshot, 3. press e.
