### ISSUE TITLE
Adding the ability to change trade ability keybind?

### ISSUE THREAD

**Issue by GetUsernameFromDatabase** [DamienShahan/LostArkFishingBot#8]
Adding the ability to change trade ability keybind?
From e to something else through config file or even to make a GUI

**Comment by DamienShahan** [comment]
Hi,

I added the feature, allowing users to set their own key bindings in a config file (resources/keybindings.yaml):\
  ![key bindings file location](https://i.imgur.com/iyarDPN.png)\
  ![key bindings file](https://i.imgur.com/GpMy9sq.png)

If you don't use a modifier (for example alt) to open the pet menu, just leave the field pet-inventory-modifier empty:\
  ![key bindings without modifier](https://i.imgur.com/KbZTbzO.png)

Thanks for the tip about .gitignore. I added that as well :)
